version: '3.6'

services:
  api:
    build: .
    container_name: api
    restart: unless-stopped
    env_file:
      - '.env'
    ports:
      - "8000:8000"
    volumes:
      - ./data/static:/static
    networks:
      - api_network

networks:
  api_network:
    driver: bridge
